# Generated by Django 3.1.4 on 2021-01-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='detail_content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
